name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - 'branch-b'

env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'  #added
    MONGO_USERNAME: superuser                                            #added 
    MONGO_PASSWORD: SuperPassword      

jobs:
    unit-testing:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS
          uses: actions/setup-node@v4
          with:
            node-version: 22

        - name: Install Dependencies
          run: npm install --no-audit

        - name: Unit Testing    #added
          run: npm test         #added  
